[toolchain]
# Requires https://github.com/rust-lang/rust/pull/130334
channel = "stage1"
components = ["rust-src"]
targets = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "aarch64-apple-ios-macabi",
]
